Database connection adn primitive configuration
CristaHo/SprintStorm pull request #5
Opened 2023-11-20 12:21 UTC by RedFoxFinn

Added database connecting capability to the SprintStorms application and primitive environment dependent configuration selection

- database URL can be provided by the environment variables
-  primitive automatic configuration selection checks the active environment (development/production) and selects correct database URL
- if no database URL is provided, exception will be invoked

2023-11-20 12:52 UTC, iritmaximus requested changes

2023-11-20 12:52 UTC, iritmaximus commented on .gitignore
> +.env.*
periaatteessa .env.* voi sallia, koska `.env.example` vois olla ihan jees sallia.

2023-11-20 12:52 UTC, iritmaximus commented on src/app.py
> +    raise Exception("No SQL URL provided")
tähän vaan joku sopiva, tarkempi virhe

2023-11-20 23:21 UTC, iritmaximus requested changes

2023-11-20 23:21 UTC, iritmaximus commented on src/app.py
> +    raise DatabaseError("No SQL URL was found. Connection cannot be made.")
Pitkän selvittelyn jälkeen selvisi, että DatabaseError on SQLAlchemyn käyttämä virhetyyppi, jota ilmeisesti ei kannata käyttää tässä tilanteessa koska pylint valittaa "orig" ja "params" puuttumisesta. Ratkaisuna ehkä käyttää KeyError tai RuntimeError, kun kyseessä env muuttujan puuttuminen. Täydellisiä ratkaisuja ei ilmeisesti ole...

2023-11-21 08:55 UTC, RedFoxFinn commented on src/app.py
> +    raise DatabaseError("No SQL URL was found. Connection cannot be made.")
Seeelvä. Korjataan kohta, kunhan aamupalaa naamariin.

2023-11-21 09:24 UTC, iritmaximus approved these changes

2023-11-21 09:25 UTC, merged